version: '3'

services:
  web:
    build: ./project
    ports:
      - "5000:5000"
    volumes:
      - myvolume:/app/data
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  myvolume:
  dbdata:

networks:
  mynetwork:
